version: "3.9"

services:
  postgres-db:
    container_name: spring-boot-demo-container
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: jacob
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5000:5432
    restart: on-failure